# Generated by Django 3.0.7 on 2020-06-17 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ques_ans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='questiongroups',
            options={'verbose_name_plural': 'Question Groups'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='answers',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='questions',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='questions',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
