# Generated by Django 3.0.7 on 2020-06-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_ans', '0002_auto_20200617_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answers',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
