# Generated by Django 3.0.7 on 2020-06-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_ans', '0003_auto_20200617_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
