# Generated by Django 3.0.7 on 2020-06-18 08:48

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('ques_ans', '0004_questions_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
