# Generated by Django 3.0.7 on 2020-06-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ques_ans', '0005_questions_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='group',
        ),
    ]
