# Generated by Django 3.0.7 on 2020-06-19 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ques_ans', '0006_remove_questions_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionGroups',
        ),
    ]
