# Generated by Django 3.0.7 on 2020-06-19 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ques_ans', '0007_delete_questiongroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_vote', models.IntegerField(choices=[(1, 'up'), (2, 'down'), (3, 'N/A')], null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ques_ans.Questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
