# Generated by Django 3.0.7 on 2020-07-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ques_ans', '0009_auto_20200619_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='upvote',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='upvote',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
