# Generated by Django 3.0.7 on 2020-07-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ques_ans', '0011_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activity/Votes'},
        ),
    ]
