# Generated by Django 3.0.7 on 2020-07-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_ans', '0012_auto_20200713_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_description',
            field=models.TextField(null=True),
        ),
    ]
