# Generated by Django 3.0.7 on 2020-07-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_ans', '0013_questions_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Question Title/Heading'),
        ),
    ]
