# Generated by Django 3.0.7 on 2020-07-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_ans', '0014_auto_20200714_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer_text',
            field=models.TextField(help_text='Write here your message!', verbose_name='Main Content'),
        ),
    ]
