# Generated by Django 3.0.7 on 2020-07-15 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ques_ans', '0015_auto_20200714_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
